### ISSUE TITLE
`dbsqlcli.main.apply_credentials_from_cfg` returns only three values when `not cfg.get("credentials")`

### ISSUE THREAD

**Issue by aucampia** [databricks/databricks-sql-cli#46]
https://github.com/databricks/databricks-sql-cli/blob/345ca09bcf602b45755a6137af5e83f9e673272f/dbsqlcli/main.py#L61-L67

This function should return four values:

https://github.com/databricks/databricks-sql-cli/blob/345ca09bcf602b45755a6137af5e83f9e673272f/dbsqlcli/main.py#L91-L94

**Comment by aucampia** [comment]
The problem this causes is:

```python
$ pipx run --spec databricks-sql-cli==0.3.0 dbsqlcli -e 'SHOW CATALOGS;'
⚠️  dbsqlcli is already on your PATH and installed at /home/iwana/.local/bin/dbsqlcli. Downloading and running anyway.
Traceback (most recent call last):
  File "/home/iwana/.local/pipx/.cache/5642ff8ce8cd645/bin/dbsqlcli", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/iwana/.local/pipx/.cache/5642ff8ce8cd645/lib64/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iwana/.local/pipx/.cache/5642ff8ce8cd645/lib64/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/iwana/.local/pipx/.cache/5642ff8ce8cd645/lib64/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iwana/.local/pipx/.cache/5642ff8ce8cd645/lib64/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iwana/.local/pipx/.cache/5642ff8ce8cd645/lib64/python3.11/site-packages/dbsqlcli/main.py", line 711, in cli
    dbsqlcli = DBSQLCli(
               ^^^^^^^^^
  File "/home/iwana/.local/pipx/.cache/5642ff8ce8cd645/lib64/python3.11/site-packages/dbsqlcli/main.py", line 92, in __init__
    hostname, http_path, access_token, auth_type = apply_credentials_from_cfg(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 4, got 3)
```

**Comment by susodapop** [comment]
I'm confused by your report since this has already been "fixed" in `main` for four months. Your example that shows only three returned items is only possible because you picked a commit older than four months. It doesn't appear anything needs to be fixed at this time. Can you double-check?

**Comment by aucampia** [comment]
> I'm confused by your report since this has already been "fixed" in main for four months. Your example that shows only three returned items is only possible because you picked a commit older than four months.

This is the code I get if I use "copy permalink" from the main branch:

https://github.com/databricks/databricks-sql-cli/blob/f02294017601b23875831143f697e59cb6858ad8/dbsqlcli/main.py#L61-L74

https://github.com/databricks/databricks-sql-cli/blob/f02294017601b23875831143f697e59cb6858ad8/dbsqlcli/main.py#L91-L94

That is from f02294017601b23875831143f697e59cb6858ad8 which is from 2 weeks ago. The code still has the same problem which I reported, which is that `if not cfg.get("credentials"):` it returns a tuple with 3 values, while trying to unpack 4. Or am I missing something?

**Comment by aucampia** [comment]
Can you create a permalink to where the problem is no longer present if it was fixed?

**Comment by aucampia** [comment]
> Your example that shows only three returned items is only possible because you picked a commit older than four months.

Both links in the issue body link to 345ca09bcf602b45755a6137af5e83f9e673272f - this commit is from the 31st of march:

![image](https://github.com/databricks/databricks-sql-cli/assets/4481387/2ec38873-b00f-466d-b7d0-7c5dfc760fcd)

I don't understand what you mean when you say I picked a four-month-old commit. What am I missing?

**Comment by aucampia** [comment]
https://github.com/databricks/databricks-sql-cli/assets/4481387/fc67a185-c1c6-4aec-a7dc-0f3cc59906fd

**Comment by aucampia** [comment]
Maybe you are not using the main branch?
